# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cache_pb2 as cache__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CacheStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCache = channel.unary_unary(
                '/Cache/GetCache',
                request_serializer=cache__pb2.GetRequest.SerializeToString,
                response_deserializer=cache__pb2.GetReply.FromString,
                _registered_method=True)
        self.SetCache = channel.unary_unary(
                '/Cache/SetCache',
                request_serializer=cache__pb2.SetRequest.SerializeToString,
                response_deserializer=cache__pb2.SetReply.FromString,
                _registered_method=True)
        self.DeleteCache = channel.unary_unary(
                '/Cache/DeleteCache',
                request_serializer=cache__pb2.DeleteRequest.SerializeToString,
                response_deserializer=cache__pb2.DeleteReply.FromString,
                _registered_method=True)


class CacheServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCache': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCache,
                    request_deserializer=cache__pb2.GetRequest.FromString,
                    response_serializer=cache__pb2.GetReply.SerializeToString,
            ),
            'SetCache': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCache,
                    request_deserializer=cache__pb2.SetRequest.FromString,
                    response_serializer=cache__pb2.SetReply.SerializeToString,
            ),
            'DeleteCache': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCache,
                    request_deserializer=cache__pb2.DeleteRequest.FromString,
                    response_serializer=cache__pb2.DeleteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Cache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Cache', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cache(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Cache/GetCache',
            cache__pb2.GetRequest.SerializeToString,
            cache__pb2.GetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Cache/SetCache',
            cache__pb2.SetRequest.SerializeToString,
            cache__pb2.SetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Cache/DeleteCache',
            cache__pb2.DeleteRequest.SerializeToString,
            cache__pb2.DeleteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
