# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"&\n\x08GetReply\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\n\n\x08SetReply\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1a\n\x0b\x44\x65leteReply\x12\x0b\n\x03num\x18\x01 \x01(\x05\x32\x82\x01\n\x05\x43\x61\x63he\x12$\n\x08GetCache\x12\x0b.GetRequest\x1a\t.GetReply\"\x00\x12$\n\x08SetCache\x12\x0b.SetRequest\x1a\t.SetReply\"\x00\x12-\n\x0b\x44\x65leteCache\x12\x0e.DeleteRequest\x1a\x0c.DeleteReply\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_GETREQUEST']._serialized_start=15
  _globals['_GETREQUEST']._serialized_end=40
  _globals['_GETREPLY']._serialized_start=42
  _globals['_GETREPLY']._serialized_end=80
  _globals['_SETREQUEST']._serialized_start=82
  _globals['_SETREQUEST']._serialized_end=122
  _globals['_SETREPLY']._serialized_start=124
  _globals['_SETREPLY']._serialized_end=134
  _globals['_DELETEREQUEST']._serialized_start=136
  _globals['_DELETEREQUEST']._serialized_end=164
  _globals['_DELETEREPLY']._serialized_start=166
  _globals['_DELETEREPLY']._serialized_end=192
  _globals['_CACHE']._serialized_start=195
  _globals['_CACHE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
